version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    open-pull-requests-limit: 5
    directory: /
    schedule:
      interval: daily
