name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

  workflow_dispatch: {}

jobs:
  race-test:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: WillAbides/setup-go-faster@v1.12.0
        with:
          go-version-file: go.mod

      - name: Cache Go files
        uses: capnspacehook/cache-go@v1

      - name: Ensure main package builds
        run: |
          go build

      - name: Run tests
        run: |
          go test -race -timeout 20m ./...
