name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

  workflow_dispatch: {}

jobs:
  race-test:
    timeout-minutes: 25
    strategy:
      matrix:
        # test with minimum supported and latest version of Go
        go-version: [1.18.x, 1.21.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: WillAbides/setup-go-faster@v1.12.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go files
        uses: capnspacehook/cache-go@v1

      - name: Ensure main package builds
        run: |
          go build

      - name: Run tests
        run: |
          go test -race -timeout 20m ./...
