name: Test

on:
  push:
    branches:
      - master
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test.yml"
  pull_request:
    branches:
      - "*"
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test.yml"

  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6.5.0
        with:
          go-version: stable
          check-latest: true
          cache: false

      - name: Restore Go cache
        uses: capnspacehook/cache-go/restore@v2.1.0

      - run: |
          echo "Testing with latest Go"
          go test

          # test repro combinations with previous minor Go version
          # TODO update this to test previous 2 versions once Go 1.27 is released
          CUR_MINOR_VER="$(go version | grep -oE 'go1\.([0-9]+)' | tr -d '\n' | tail -c 2)"
          for i in 1; do
            GO_VER="go1.$((CUR_MINOR_VER - i)).0"
            echo "Testing with $GO_VER"
            GOTOOLCHAIN="$GO_VER" go test -run TestReproMatrix
          done

      - name: Save Go cache
        if: always()
        uses: capnspacehook/cache-go/save@v2.1.0
